### ISSUE TITLE
Only finds current directory as include file.

### ISSUE THREAD

**Issue by mijoharas** [redguardtoo/cpputils-cmake#50]
I have a project where the only files added to `flycheck-clang-include-path` are:

```
flycheck-clang-include-path=(<current_directory> /usr/src/linux/include/)
```

It seems that `cpputils-cmake` is incorrectly parsing the include directories. which are included with `INCLUDE_DIRECTORIES(${MY_INCLUDE_DIRECTORIES})` which has been created with:

```
LIST(APPEND MY_INCLUDE_DIRECTORIES 
	${FOO_INCLUDE} 
	${CMAKE_CURRENT_SOURCE_DIR}/include 
	${CMAKE_CURRENT_SOURCE_DIR}/thirdparty)
```

Reading through the code, I can't quite see where this should be parsed. Am I misunderstanding that this should be added to the `flycheck-clang-include-path`?

**Comment by redguardtoo** [comment]
ｃｈｅｃｋ　ＲＥＡＤＭＥ　ｆｏｒ　ｔｈｅ　ｄｅｂｕｇ　ｗｏｒｋｆｌｏｗ　ａｎｄ　ｓｅｎｄ　ｍｅ　ｍｏｒｅ　ｄｅｔａｉｌｓ．

ｂａｓｉｃａｌｌｙ　ｍｙ　ｐａｃｋａｇｅ　ｄｏ　ｎｏｔ　ｐａｒｓｅ　ｉｎｃｌｕｄｅ　ｄｉｒｅｃｔｏｒｙ，　ｃｍａｋｅ　ｗｉｌｌ　ｃｒｅａｔｅ　ｆｌａｇｓ．ｍａｋｅ　ａｎｄ　Ｉ　ｗｉｌｌ　ｒｅａｄ　ｆｒｏｍ　ｉｔ．

Ｓｏ　ｅｉｔｈｅｒ　ｃｍａｋｅ　ｄｏｅｓ　ｎｏｔ　ｗｏｒｋ　ｃｒｅａｔｅ　ｆｌａｇｓ．ｍａｋｅ　ｏｒ　Ｉ　ｃａｎｎｏｔ　ｆｉｎｄ　ｉｔ．

**Comment by mijoharas** [comment]
Thanks for getting back to me. so for my project build folder (e.g. `<project_root>/build` I have a folder called `proj_tmp` which contains CMakeFiles for all the different targets in nested directory structures. (e.g. `<project_root>/build/<my_module_name>/CMakeFiles/<individual_target_name>/flags.make` where the target is stuff like `core_utils.dir` and other things specific to my project (but with `.dir` as a suffix)) Should `cpputils-cmake` be able to find these?

**Comment by redguardtoo** [comment]
run `find . -name flags.make -o -name CMakeLists.txt -type f -print0 | tar -czvf build.tar.gz --null -T -` at the parent directory of both source and build. send the build.tar.gz to me.

**Comment by mijoharas** [comment]
That won't print any `flags.make` files. you need a second `-print0` next to the `flags.make`:
```
find . -name flags.make -o -name CMakeLists.txt -type f -print0 | grep flags | wc -l
# returns 0
```
```
find . -name flags.make -o -print0 -name CMakeLists.txt -type f -print0 | grep flags | wc -l
# returns 1
```
I'll send you the output of the below modified command. one second.
```
find . -name flags.make -print0 -o -name CMakeLists.txt -type f -print0 | tar -czvf build.tar.gz --null -T -
```

**Comment by mijoharas** [comment]
also, I just had a look, and that copies all of my CMakeLists.txt and flags.make to the `.tar.gz`. Unfortunately I can't do that. Sorry. :smile:. Is there any way we can figure out what's going on without that. I can send you the (slightly modified) directory structure and then if you tell me how the files are parsed I can check if that works and test the individual elements of that parsing to see why it fails, or figure out why it fails to find the files if that is the case.

**Comment by redguardtoo** [comment]
just follow the steps on readme and send me the debug logging

**Comment by stepanbujnak** [comment]
I had the same problem, it turned out that I needed to run `cmake` and `make` successfully, i.e. the executable/library must've been created in order to get this extension working. Is this really necessary though? I mean, all that's necessary is the `flags.make` file which is created while running `cmake`. Requiring an actual binary/library to run the extension is redundant.

**Comment by redguardtoo** [comment]
Yes, it's necessary, because Clang doesn't work if you have any compiling error, besides flymake+gcc, compiling is necessary step to make sure you actually include ALL headers.

**Comment by stepanbujnak** [comment]
But isn't it flycheck's job to help out with compiling errors? Flycheck shouldn't work only when the project has been successfully compiled, and parsing `flags.make` in order to set `flycheck-clang-include-path` and `flycheck-clang-definitions` shouldn't require pre-built binary/library.

**Comment by redguardtoo** [comment]
unless you compile the program at least once successfully, you are not sure you include ALL the necessary headers. 

After you feed ALL the necessary header directories to flycheck, it will work by checking the errors in your cpp files.

I know in theory you don't need compile the program at first. but in practice when dealing with big project, it's always wise to make sure compile result is 100% correct at first

**Comment by stepanbujnak** [comment]
Fair enough, but a warning message that `Hey, you need to compile your project first!` would be nice.

**Comment by redguardtoo** [comment]
Yeah, doable this weekend
