### ISSUE TITLE
what is the suggested project orgnisation?

### ISSUE THREAD

**Issue by autosquid** [redguardtoo/cpputils-cmake#52]
In the example give, cmakelist.txt are separated from source files (cpps & hpps), can I mix them together?  

In my little project, there's always an error saying "build directory is not found" which dissappears aftering removing this package, and it make my binary output in build dir. as a directory.

following is my project structure:

```
├── CMakeLists.txt
├── bin
│   └── ProgeoDemo
├── build
├── data
│   └── scanner_test.pas
└── src
    ├── CMakeLists.txt
    ├── GPATH
    ├── GRTAGS
    ├── GTAGS
    ├── Makefile
    ├── dictionary.cpp
    ├── dictionary.h
    ├── error.cpp
    ├── error.h
    ├── main.cpp
    ├── py
    │   └── cylindar.py
    ├── scanerdemo.cpp
    ├── scanner.cpp
    ├── scanner.h
    ├── scanner_test.pas
    ├── token.cpp
    └── token.h
```

**Comment by redguardtoo** [comment]
that's fine.
make sure you compile your project in build directory successfully at first.
