### ISSUE TITLE
Compile in current exe dir and Makefile generation for Flymake in directories where Libraries are the only targets

### ISSUE THREAD

**Issue by deuscovrigus** [redguardtoo/cpputils-cmake#53]
I am trying to force cppcm to generate Makefiles in directories containing CMakeLists.txt where only ADD_LIBRARY is called. Is this possible ? Every time I open a source from such a directory cppcm fails to complete, initiate flymake etc. Is this a bug or a feature? Is cppcm designed to work only for directories where ADD_EXECUTABLE is called?

**Comment by redguardtoo** [comment]
add_library is supported

reproduce issue in a minimum project, and more information on dev environment

**Comment by redguardtoo** [comment]
You can find `example/` project here where we build mylib2 from moreclasses.cpp. As you can see from screenshot, cpputils-cmake works.

cpputils-cmake just do one thing, find the location of C++ headers, check the README for the steps to debug. The auto-completion plugins (I use company-mode) decides the actual complete thing.

![screen shot 2015-06-19 at 3 50 17 pm](https://cloud.githubusercontent.com/assets/184553/8247905/723c2c14-169b-11e5-8218-eda2d3b0e49b.png)

**Comment by deuscovrigus** [comment]
Ok I actually got it to work after I noticed that the project I'm working  on (http://sourceforge.net/projects/vxl/)  installs targets (i.e. vnl) via the CMake directive
INSTALL_TARGETS(/lib vnl). With the FAQ suggestion in the readme, i setup a version of
cppcm-get-executable-full-path-callback in my .emacs where I modified the returned path to be a function of the cppcm-build-dir as such,
 (t (setq path (concat cppcm-build-dir "lib/" file)).
Flymake works well now. However, when attempting to build a specific target via cppcm-compile-in-current-exe-dir, the build string attempts to build the target into <Project_Build_dir>/lib where there is no Makefile ( it's an install directory after all). Ideally it would be nice to form the build string to be calling make in the directory where the library/executable should be if INSTALL_TARGETS(/lib vnl) wouldn't have been called.
For example, with INSTALL_TARGETS(/lib vnl) this is what I get:

make -C "/Users/deuscovrigus/Documents/engn2912b/vxl_lite/build_unix/lib/libvnl_algo.a"

when in fact it should be 
make -C "/Users/deuscovrigus/Documents/engn2912b/vxl_lite/build_unix/core/vnl/"
the directory where the Makefile for building the target libvnl_algo actually exists.

Is there a way to have this feature?

**Comment by redguardtoo** [comment]
Yes, I will consider implement this in next release. Could you set up a minimum example to reproduce this issue?

**Comment by deuscovrigus** [comment]
Yes I have edited the example from the source to reproduce the issue. Can I attach it here as a zip?

**Comment by deuscovrigus** [comment]
Attached is the minimal example
Without this fallback function cppcm will not be able to create the flymake Makefile or initiate the compilation command cppcm-compile-in-current-exe-dir:

(setq cppcm-get-executable-full-path-callback
      (lambda (path type tgt-name)
        ;; path is the supposed-to-be target's full path
        ;; type is either add_executabe or add_library
        ;; tgt-name is the target to built. The target's file extension is stripped
        (message "cppcm-get-executable-full-path-callback called => %s %s %s" path type tgt-name)
        (let ((dir (file-name-directory path))
              (file (file-name-nondirectory path)))
          (cond
           ((string= type "add_executable")
            (setq path (concat cppcm-build-dir "bin/" file)))
           ;; for add_library
           (t (setq path (concat cppcm-build-dir "lib/" file)))
           ))
        ;; return the new path
        (message "cppcm-get-executable-full-path-callback called => path=%s" path)
        path))
Maybe with some elisp magic the cmake directive INSTALL_TARGETS can be parsed and the paths can be added to the fallback path lookup?


Adding this will make it work, however, cppcm-compile-in-current-exe-dir will yield:

make -C "/Users/deuscovrigus/.emacs.d/plugins/cpputils/example/build_unix/lib/libmylib2.dylib”
when ideally it should be

make -C "/Users/deuscovrigus/.emacs.d/plugins/cpputils/example/build_unix/lib/project_z/“ 
where the actual Makefile is.

Best,
-Octi

**Comment by redguardtoo** [comment]
can't get the example. email it to chenbin.sh AT gmail.com

**Comment by redguardtoo** [comment]
`cppcm-get-exe-dir-path-current-buffer` is for compile

**Comment by deuscovrigus** [comment]
Ok I tested the new version and right now I adjust the path to match a desired directory when I call compile. Fyi, in the minimum example I sent you, flymake won't start under this most recent revision. Let me know if you want me to email it to you again.
Regardless, great work! And I apologize for the delay

**Comment by redguardtoo** [comment]
It's Makefile created? flymake use the Makefile created by cpputils-cmake
