### ISSUE TITLE
M-x cppcm-compile 默认路径不对

### ISSUE THREAD

**Issue by dulm** [redguardtoo/cpputils-cmake#54]
用hello的例子是 make -C hello/build/main/
期待的应该是 make -C hello/build/

(defun cppcm-get-exe-dir-path-current-buffer ()
  (file-name-directory (cppcm-get-exe-path-current-buffer))
  (cppcm-get-exe-path-current-buffer))

应该这里要加一个取parent dir的操作。
lisp新手，所以还看不懂这里第一句操作是干嘛用，猜测不会对cppcm-get-exe-path-current-buffer返回值修改，是否是多余的？

**Comment by redguardtoo** [comment]
d11e549 correct executable directory be used v0.5.2 (Chen Bin)
