### ISSUE TITLE
system path is gone after (cppcm-reload-all)

### ISSUE THREAD

**Issue by ziyangli** [redguardtoo/cpputils-cmake#56]
Hello Chen Bin,

These days I have been trying to configure my Emacs for auto completion (especially when I have **include** folder in the project) and your package finally make it work. Thank you.

However, after `M-x cppcm-reload-all`, I am not able to auto complete things from system headers anymore and I think the following is the reason:

```
company-c-headers-path-system is a variable defined in `company-c-headers.el'.
Its value is
("/home/lzy/catkin_ws/src/demo/src/" "/home/lzy/catkin_ws/src/demo/include" "/opt/ros/indigo/include" "/usr/include/qt" "/usr/include/qt/QtCore" "/usr/lib/qt/mkspecs/linux-g++" "/usr/include/qt/QtNetwork")

Original value was 
("/usr/include/" "/usr/local/include/")
```

so system path is gone and that should not happen, right?

Actually, the result of 
```
echo "" | g++ -v -x c++ -E - 
```

should always be in the path, in my opinion.

**Comment by redguardtoo** [comment]
You can use `cppcm-extra-preprocess-flags-from-user` which will be respected by cpputils-cmake.

`(setq cppcm-extra-preprocss-flags-from-user '("-I/usr/src/linux/include" "-DNDEBUG"))`
