### ISSUE TITLE
Slightly different directory structure

### ISSUE THREAD

**Issue by agauniyal** [redguardtoo/cpputils-cmake#60]
`Executable missing. Current directory is ..../src` which should be `../build` for my project.

Some of my projects have such directory structure:

```
--build

--src
----somefiles.cpp
----somefiles.h

--lib
----someotherfiles.o

--test
----testfile.hpp

--CMakeLists.txt
--build.sh
```

CMakeLists.txt contains : 
```
include_directories(src)
...
...
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)
```

& build.sh contains

```
#!/usr/bin/env bash

set -ex

mkdir -p build
cd build/
cmake ..
make
```

In short, my `cpp` files are usually in `src`, header files and library files have diff folders as well & I build project in seperate `build` folder and `build/bin` contains executable. Therefore I use `build.sh` which creates build directory and then calls `cmake ..` on it. This creates tyical workflow problem with cpputils-cmake plugin. Because whenever I compile my project, it never finds the build directory and starts cmake in current `src` directory where my cpp files are (which I'm editing). How should I solve this problem?

**Comment by agauniyal** [comment]
Now somehow it works but dosen't loads binary with C-c C-g because it searches it inside build directory. 

`set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)`

Should search inside `build/bin`.

**Comment by redguardtoo** [comment]
check https://github.com/redguardtoo/cpputils-cmake#customize-target-path

Just double check, `cppcm-include-dirs` should be non-empty, is it?

**Comment by agauniyal** [comment]
BTW I was reading through and found out that I don't have any files in any of the directory mentioned in this code:

```
(add-hook 'c-mode-common-hook
          (lambda ()
            (if (derived-mode-p 'c-mode 'c++-mode)
                (if  (not (or (string-match "^/usr/local/include/.*" buffer-file-name)
                              (string-match "^/usr/src/linux/include/.*" buffer-file-name)))
                    (cppcm-reload-all))
              )))
```

Instead my system files are in `/usr/include` only. Eg. `/usr/include/c++/5.2.0/....` .

**Comment by agauniyal** [comment]
>check https://github.com/redguardtoo/cpputils-cmake#customize-target-path
Just double check, cppcm-include-dirs should be non-empty, is it?

This fixes it. But it should be built in, parse CMakeLists.txt and then detect executable automatically. If it's not too hard hehe :+1:
