### ISSUE TITLE
support for company irony c headers?

### ISSUE THREAD

**Issue by agauniyal** [redguardtoo/cpputils-cmake#62]
https://github.com/hotpxl/company-irony-c-headers

**Comment by redguardtoo** [comment]
Thanks for the head up, I'm considering support related plugins.

**Comment by agauniyal** [comment]
This will complete the whole irony server completion family plugins :smile: :+1: .

**Comment by ddovod** [comment]
Hi there. Any updates on this issue? Sounds like a very useful addition!

**Comment by redguardtoo** [comment]
maybe this weekend.

**Comment by ddovod** [comment]
It would be great! Thank you a lot!

**Comment by ddovod** [comment]
Wow, is this feature implemented now?
