### ISSUE TITLE
clang error in emacs 24.5

### ISSUE THREAD

**Issue by smallst** [redguardtoo/cpputils-cmake#65]
当头文件和cpp文件不在同一个目录下时，结构体内部元素/函数 无法自动补全

我看了所以closed issue，很多人都提到了clang error，但是依然没有找到适合我的解决办法。

我使用的是你的.emacs.d,下载了你的example，改名成build之后在build文件夹里cmake . 和make，
但打开src/main.cpp 后尝试 cls.  出现
 clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -I/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src/ -Xclang -code-completion-at=-:16:9 -
但如果是同文件夹下的.h文件里定义的结构体就能正常补全。
以下是debug的内容:

cppcm-reload-all called
cppcm-get-dirs called
cppcm-query-var-from-last-matched-line called [2 times]
(cppcm-get-dirs)=(t nil /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/ /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build) [2 times]
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
CMakeLists.txt=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeLists.txt
possible-targets=((add_executable project_x_exe))
cppcm-handle-one-executable called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/ /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build (add_executable project_x_exe)
cppcm--guess-dir-containing-cmakelists-dot-txt called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build
cppcm--guess-dir-containing-cmakelists-dot-txt: dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build
flag-make=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/project_x_exe.dir/flags.make
cppcm-proj-max-dir-level called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/ (add_executable project_x_exe)
cppcm-guess-exe-full-path: type=add_executable
cppcm-guess-exe-full-path: tgt=(add_executable project_x_exe)
cppcm-guess-exe-full-path: exe-dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-guess-exe-full-path: cppcm-cmake-target-regex=^ *[^#]* *\(add_executable\|add_library\) *( *\([^ ]+\)
cppcm-guess-exe-full-path: base-exe-name=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/libproject_x_exe
exe-full-path=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_x_exe
cppcm-trim-compiling-flags called => 
tks=nil
queried-c-flags=CXX_FLAGS =  
is-c=CXX
c-flags=
queried-c-defines=CXX_FLAGS =  
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/3.4.1 /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/3.4.1/CompilerIdC /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/3.4.1/CompilerIdCXX /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/CMakeTmp /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/project_x_exe.dir /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/CMakeFiles/project_x_exe.dir/src /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
CMakeLists.txt=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/CMakeLists.txt
possible-targets=((add_library mylib1))
cppcm-handle-one-executable called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/ /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a (add_library mylib1)
cppcm--guess-dir-containing-cmakelists-dot-txt called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a
cppcm--guess-dir-containing-cmakelists-dot-txt: dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a
flag-make=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/CMakeFiles/mylib1.dir/flags.make
cppcm-proj-max-dir-level called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/ (add_library mylib1)
cppcm-guess-exe-full-path: type=add_library
cppcm-guess-exe-full-path: tgt=(add_library mylib1)
cppcm-guess-exe-full-path: exe-dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/
cppcm-guess-exe-full-path: cppcm-cmake-target-regex=^ *[^#]* *\(add_executable\|add_library\) *( *\([^ ]+\)
cppcm-guess-exe-full-path: base-exe-name=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/libmylib1
cppcm--find-physical-lib-file called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/libmylib1
cppcm--find-physical-lib-file return =/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/libmylib1.so
exe-full-path=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/libmylib1.so
cppcm-trim-compiling-flags called => -fPIC  
tks=(-fPIC)
queried-c-flags=CXX_FLAGS = -fPIC  
is-c=CXX
c-flags=
queried-c-defines=CXX_FLAGS = -fPIC  
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/CMakeFiles /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/CMakeFiles/mylib1.dir /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/CMakeFiles/mylib1.dir/src /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/src /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
CMakeLists.txt=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/CMakeLists.txt
possible-targets=((add_library mylib2))
cppcm-handle-one-executable called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/ /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z (add_library mylib2)
cppcm--guess-dir-containing-cmakelists-dot-txt called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z
cppcm--guess-dir-containing-cmakelists-dot-txt: dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z
flag-make=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/CMakeFiles/mylib2.dir/flags.make
cppcm-proj-max-dir-level called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/ (add_library mylib2)
cppcm-guess-exe-full-path: type=add_library
cppcm-guess-exe-full-path: tgt=(add_library mylib2)
cppcm-guess-exe-full-path: exe-dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/
cppcm-guess-exe-full-path: cppcm-cmake-target-regex=^ *[^#]* *\(add_executable\|add_library\) *( *\([^ ]+\)
cppcm-guess-exe-full-path: base-exe-name=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/libmylib2
cppcm--find-physical-lib-file called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/libmylib2
cppcm--find-physical-lib-file return =/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/libmylib2.so
exe-full-path=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/libmylib2.so
cppcm-trim-compiling-flags called => -fPIC  
tks=(-fPIC)
queried-c-flags=CXX_FLAGS = -fPIC  
is-c=CXX
c-flags=
queried-c-defines=CXX_FLAGS = -fPIC  
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/CMakeFiles /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/CMakeFiles/mylib2.dir /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/CMakeFiles/mylib2.dir/src /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/src /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-scan-info-from-cmake called => /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src /home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
cppcm-set-c-flags-current-buffer called
cppcm--guess-dir-containing-cmakelists-dot-txt called => nil
cppcm--guess-dir-containing-cmakelists-dot-txt: dir=/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/
c-compiling-flags-list=( )
cppcm-include-dirs=(-I"/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src/")
ac-clang-flags=(-I/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src/)
company-clang-arguments=(-I/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src/)
flycheck-clang-include-path=(/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src/)
flycheck-clang-definitions=nil
company-c-headers-path-system=(/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/src/)

-----
cppcm-hash is a variable defined in `cpputils-cmake.el'.
Its value is #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data
              ("/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/exe-full-path" "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_x_exe" "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/cpp-flags"
               ("" "")
               "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/exe-full-path" "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/libmylib1.so" "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_a/cpp-flags"
               ("" "-Dmylib1_EXPORTS")
               "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/exe-full-path" "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/libmylib2.so" "/home/smallst/Documents/c++doc/cpputils-cmake-master/cpputils-cmake-master/build/project_z/cpp-flags"
               ("" "-Dmylib2_EXPORTS")))

-----
cpputils-cmake version ：0.5.2
-----
emacs version:

GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
for more information about these matters, see the file named COPYING.
-----
OS:
Arch Linux on x86-64 Linux 4.2.5-1-ARCH

同时，flycheck（flymake？）会报（不在同一目录下且没有在include里标明路径的）头文件不存在的error，当cmake 并make之后消失，一旦修改cpp文件（如测试 cls. )即使未保存也会再次报头文件不存在的错，并且如果不重新cmake ，make也会出错，不知是否是我没有掌握cmake的正确使用方法？

**Comment by redguardtoo** [comment]
example 下创建一个空的build目录,然后参考cmake的工作流.

**Comment by smallst** [comment]
看起来问题并没有被改善
查看了build下的CMakefiles里面的flags.make发现CXX_INCLUDE都没有问题，但在src目录下修改main.cpp时依然不能自动补全cls的函数

**Comment by smallst** [comment]
找到了问题的来源
   即include头文件时是否使用正确路径。
由于使用#include "xxx.h"时c语言会自动向上级寻找头文件，此时如果xxx.h的正确目录是
"../include/xxx.h" 也是能够正确编译的。但是在此种情况下cpputils-cmake会无法正常工作，
具体表现为：
1。flymake 发现include头文件 有误，并无法找出之后的错误（如一行语句末尾不打分号），但C-x,C-o可正确打开头文件 （如果include使用正确路径，则flymake不报错，并可以正常使用）
2。company-clang无法正确补全定义在头文件中的结构体，并报clang error，但如果在C-x,C-o打开头文件之后，就可以自动补全

由于错误原因来自不规范的头文件include方式，大概不能算作配置文件的bug，只是记录一下，以便以后如果有和我一样问题的用户也能发现问题的原因
