### ISSUE TITLE
cpputils-cmake not work in window emacs with cygwin

### ISSUE THREAD

**Issue by EnjoyYouth** [redguardtoo/cpputils-cmake#77]
I use windows native emacs 26.1 and cygwin64 on windows 10.I also add E:\Cygwin\bin to environment variable PATH.But there is something bother me, when i edit c++ file. 
At first, when i open c++ file, i got this information:
`Company backend ’company-clang’ could not be initialized: Company found no clang executable`
this is clang information in cygwin:
![image](https://user-images.githubusercontent.com/39292754/50816675-3e9e6e00-135c-11e9-9115-9906ac70dd75.png)
this is clang information in `E:\Cygwin\bin`: 
![image](https://user-images.githubusercontent.com/39292754/50816773-8a511780-135c-11e9-857f-af52057774cc.png)
there is no clang.exe but a clang file(don't know what it is), could you give me some advice about this.

The `cpputils-cmake` bug report as below:
 cppcm-reload-call output
`cppcm-reload-all called
cppcm-get-dirs called
cppcm-query-var-from-last-matched-line called [2 times]
(cppcm-get-dirs)=(t nil e:/cygwin/home/shugu/hello/example/build/ /home/shugu/hello/example/src) [2 times]
cppcm-scan-info-from-cmake called => /home/shugu/hello/example/src /home/shugu/hello/example/src e:/cygwin/home/shugu/hello/example/build/
Failed to get some information from scanning. Continue anyway.
cppcm-include-dirs=nil`
cppcm-hash
`cppcm-hash is a variable defined in ‘cpputils-cmake.el’.
Its value is #<hash-table equal 0/65 0x2e97b05>
`
cppcm-version 0.5.5

**Comment by redguardtoo** [comment]
Window Emacs will open an invisible *DOS* window and try to run cli program `clang.exe` in that dos shell

So there are two problems here:
1. there is NO `clang.exe` 
2. the path  `cpputils-cmake` extracted is unix path. A windows program can't open unix file path in DOS   

If you use native windows Emacs, see http://blog.binchen.org/posts/emacs-as-c-ide-easy-way.html

Personally I don't recommend doing Java/C++/C# on Windows.

**Comment by redguardtoo** [comment]
Or check https://nilsdeppe.com/posts/emacs-c++-ide2 
Another solution from professional C++ developer.

**Comment by EnjoyYouth** [comment]
Thanks! I'll try it.
